### ISSUE TITLE
Is there a example of usage?

### ISSUE THREAD

**Issue by inNetto** [BitTheCat/tailwind-vue-data-table#20]
![image](https://github.com/BitTheCat/tailwind-vue-data-table/assets/6520049/9596eccc-6eef-4cf2-96a7-fd58858d93d9)

![image](https://github.com/BitTheCat/tailwind-vue-data-table/assets/6520049/76874656-5957-44a0-a617-6fa648faa5b7)

![image](https://github.com/BitTheCat/tailwind-vue-data-table/assets/6520049/d782194f-b41e-4915-b262-378f87cb8f30)

![image](https://github.com/BitTheCat/tailwind-vue-data-table/assets/6520049/ceda4bf2-2e98-45d7-80d1-8319dc7e14a7)

![image](https://github.com/BitTheCat/tailwind-vue-data-table/assets/6520049/b6b23e29-d3d4-4118-aa9e-1482c0f604c6)

**Comment by inNetto** [comment]
how to show row values?

**Comment by BitTheCat** [comment]
Hi @inNetto,
in the table, the field you call props is key as written in the documentation or in the file [TableShow.vue](https://github.com/BitTheCat/tailwind-vue-data-table/blob/main/dev/TableShow.vue).

```
[
    {
        label: 'id',
        key: 'id',
        sortable: true
    },
  
]
```
for more detailed information use the link to the [docs ](https://www.bitthecat.it/tailwind-vue-data-table.html)(as soon as I have a moment, I will try to move it to vercel with implementations on the docs as well)
